version: '3'

services:
  frontend:
    build: .
    command: npm run serve
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app

  database:
    image: mysql:8.0
    container_name: aws-capacity-database
    command: --default-authentication-plugin=mysql_native_password --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: rootdatabase
      MYSQL_DATABASE: AWS-Metrics
      MYSQL_USER: squarelab
      MYSQL_PASSWORD: rootdatabase
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    volumes:
      - ./database:/var/lib/mysql